default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost

devtest: &devtest
  username: <%= Rails.application.credentials.pg.database_user %>
  password: <%= Rails.application.credentials.pg.database_pwd %>

development:
  <<: *default
  <<: *devtest
  database: rails_chat_development

test:
  <<: *default
  <<: *devtest
  database: rails_chat_test

production:
  <<: *default
  database: rails_chat_production