login: &login
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: stels
  password: 123456

development:
  <<: *login
  database: socket_chat_development

test:
  <<: *login
  database: socket_chat_test

production:
  <<: *login
  database: socket_chat_production