login: &login
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PWD'] %>

development:
  <<: *login
  database: rails_chat_development

test:
  <<: *login
  database: rails_chat_test

production:
  <<: *login
  database: rails_chat_production